/** サイドメニュー */
export const SIDE_MENU = [
  {
    label: "TOP",
    title: "TOP",
    iconClass: "u-icon__top",
    link: "/",
    to: "/",
    currentRouteName: "top",
    icon: "mdi-apps",
  },
  {
    label: "ABOUT",
    title: "ABOUT",
    iconClass: "u-icon__about",
    link: "/about",
    to: "/about",
    currentRouteName: "about",
    icon: "mdi-chart-bubble",
  },
  {
    label: "SKILL",
    title: "SKILL",
    iconClass: "u-icon__skill",
    link: "/skill",
    to: "/skill",
    currentRouteName: "skill",
    icon: "mdi-chart-bubble",
  },
  {
    label: "PORTFOLIO",
    title: "PORTFOLIO",
    iconClass: "u-icon__skill",
    link: "/portfolio",
    to: "/portfolio",
    currentRouteName: "portfolio",
    icon: "mdi-chart-bubble",
  },
  {
    label: "CONTACT",
    title: "CONTACT",
    iconClass: "u-icon__contact",
    link: "/contact",
    to: "/contact",
    currentRouteName: "contact",
    icon: "mdi-chart-bubble",
  },
]
